# Generated by Django 4.2 on 2023-06-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_alter_productimages_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='99.99', max_digits=999999999999)),
                ('weightsize', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ws', to='ecomapp.product')),
            ],
            options={
                'verbose_name_plural': 'Weight/Size',
            },
        ),
    ]
