# Generated by Django 4.2.2 on 2023-06-26 16:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='I am a product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='I am a vendor', null=True),
        ),
    ]
